"use strict";
const COLS=10,ROWS=20,EMPTY="";
const SHAPES=[{color:"cyan",cells:[[0,0],[1,0],[2,0],[3,0]]},{color:"yellow",cells:[[0,0],[1,0],[0,1],[1,1]]},{color:"violet",cells:[[1,0],[0,1],[1,1],[2,1]]},{color:"lime",cells:[[1,0],[2,0],[0,1],[1,1]]},{color:"red",cells:[[0,0],[1,0],[1,1],[2,1]]},{color:"blue",cells:[[0,0],[0,1],[1,1],[2,1]]},{color:"orange",cells:[[2,0],[0,1],[1,1],[2,1]]}];
const $=id=>document.getElementById(id),blank=()=>Array.from({length:ROWS},()=>Array(COLS).fill(EMPTY));
const makePiece=()=>{const s=SHAPES[Math.floor(Math.random()*SHAPES.length)];return{color:s.color,cells:s.cells.map(c=>[...c]),x:3,y:0}};
let board=blank(),piece=makePiece(),next=makePiece(),score=0,lines=0,best=Number(localStorage.getItem("neon-blocks-best")||0),started=false,paused=false,timer;
function valid(p,grid=board){return p.cells.every(([cx,cy])=>{const x=p.x+cx,y=p.y+cy;return x>=0&&x<COLS&&y>=0&&y<ROWS&&!grid[y][x]})}
function render(){const view=board.map(r=>[...r]);if(started)piece.cells.forEach(([cx,cy])=>{const x=piece.x+cx,y=piece.y+cy;if(y>=0&&y<ROWS&&x>=0&&x<COLS)view[y][x]=piece.color});$("board").innerHTML=view.flat().map(c=>`<span class="cell ${c?`filled ${c}`:""}"></span>`).join("");$("next").innerHTML=Array.from({length:8},(_,i)=>{const x=i%4,y=Math.floor(i/4),on=next.cells.some(([cx,cy])=>cx===x&&cy===y);return `<span class="cell ${on?`filled ${next.color}`:""}"></span>`}).join("");$("score").textContent=score.toLocaleString("es-ES");$("lines").textContent=String(lines).padStart(2,"0");$("level").textContent=String(Math.floor(lines/10)+1).padStart(2,"0");$("best").textContent=best.toLocaleString("es-ES");$("pauseTop").textContent=paused?"▶":"Ⅱ"}
function schedule(){clearInterval(timer);if(started&&!paused)timer=setInterval(()=>move(0,1),Math.max(110,720-Math.floor(lines/10)*70))}
function start(){board=blank();piece=makePiece();next=makePiece();score=0;lines=0;started=true;paused=false;$("overlay").classList.add("hidden");render();schedule()}
function finish(){started=false;clearInterval(timer);best=Math.max(best,score);localStorage.setItem("neon-blocks-best",best);$("overlayLabel").textContent="FIN DE PARTIDA";$("overlayTitle").textContent=score.toLocaleString("es-ES");$("startButton").textContent="JUGAR OTRA VEZ";$("overlay").classList.remove("hidden");render()}
function lock(){piece.cells.forEach(([cx,cy])=>{const x=piece.x+cx,y=piece.y+cy;if(y>=0)board[y][x]=piece.color});const kept=board.filter(row=>row.some(c=>!c)),cleared=ROWS-kept.length;while(kept.length<ROWS)kept.unshift(Array(COLS).fill(EMPTY));board=kept;score+=[0,100,300,500,800][cleared]*(Math.floor(lines/10)+1);lines+=cleared;piece=next;piece.x=3;piece.y=0;next=makePiece();if(!valid(piece))finish();else{render();schedule()}}
function move(dx,dy){if(!started||paused)return;const p={...piece,x:piece.x+dx,y:piece.y+dy};if(valid(p)){piece=p;render()}else if(dy>0)lock()}
function rotate(){if(!started||paused)return;const cells=piece.cells.map(([x,y])=>[1-y,x]);for(const kick of [0,-1,1,-2,2]){const p={...piece,cells,x:piece.x+kick};if(valid(p)){piece=p;render();return}}}
function drop(){if(!started||paused)return;const initial=piece.y;while(valid({...piece,y:piece.y+1}))piece.y++;score+=(piece.y-initial)*2;lock()}
function togglePause(){if(!started)return;paused=!paused;if(paused){clearInterval(timer);$("overlayLabel").textContent="EN PAUSA";$("overlayTitle").textContent="PAUSA";$("startButton").textContent="CONTINUAR";$("overlay").classList.remove("hidden")}else{$("overlay").classList.add("hidden");schedule()}render()}
$("startButton").addEventListener("click",()=>paused?togglePause():start());$("pauseTop").addEventListener("click",togglePause);
document.addEventListener("keydown",e=>{if(["ArrowLeft","ArrowRight","ArrowDown","ArrowUp"," "].includes(e.key))e.preventDefault();if(e.key==="ArrowLeft")move(-1,0);if(e.key==="ArrowRight")move(1,0);if(e.key==="ArrowDown")move(0,1);if(e.key==="ArrowUp"||e.key.toLowerCase()==="x")rotate();if(e.key===" ")drop();if(e.key.toLowerCase()==="p")togglePause()});
document.querySelectorAll("[data-action]").forEach(button=>button.addEventListener("pointerdown",()=>({left:()=>move(-1,0),right:()=>move(1,0),down:()=>move(0,1),rotate,drop}[button.dataset.action]())));render();
